// Auto-generated by configure
#if __APPLE__
  #if __has_include(<leptonica/allheaders.h>)
    #include <leptonica/allheaders.h>
  #elif __has_include(<allheaders.h>)
    #include <allheaders.h>
  #else
    #error "Could not find allheaders.h"
  #endif
#else
  #include <allheaders.h>
#endif
