# Generated by cpp11: do not edit by hand

tesseract_major_version <- function() {
  .Call(`_cpp11tesseract_tesseract_major_version`)
}

tesseract_config <- function() {
  .Call(`_cpp11tesseract_tesseract_config`)
}

tesseract_engine_internal <- function(datapath, language, confpaths, opt_names, opt_values) {
  .Call(`_cpp11tesseract_tesseract_engine_internal`, datapath, language, confpaths, opt_names, opt_values)
}

tesseract_engine_set_variable <- function(ptr, name, value) {
  .Call(`_cpp11tesseract_tesseract_engine_set_variable`, ptr, name, value)
}

validate_params <- function(params) {
  .Call(`_cpp11tesseract_validate_params`, params)
}

engine_info_internal <- function(ptr) {
  .Call(`_cpp11tesseract_engine_info_internal`, ptr)
}

print_params <- function(filename) {
  .Call(`_cpp11tesseract_print_params`, filename)
}

get_param_values <- function(api, params) {
  .Call(`_cpp11tesseract_get_param_values`, api, params)
}

ocr_raw <- function(input, ptr, HOCR) {
  .Call(`_cpp11tesseract_ocr_raw`, input, ptr, HOCR)
}

ocr_file <- function(file, ptr, HOCR) {
  .Call(`_cpp11tesseract_ocr_file`, file, ptr, HOCR)
}

ocr_raw_data <- function(input, ptr) {
  .Call(`_cpp11tesseract_ocr_raw_data`, input, ptr)
}

ocr_file_data <- function(file, ptr) {
  .Call(`_cpp11tesseract_ocr_file_data`, file, ptr)
}

n_pages <- function(file_path, opw, upw) {
  .Call(`_cpp11tesseract_n_pages`, file_path, opw, upw)
}

get_poppler_config <- function() {
  .Call(`_cpp11tesseract_get_poppler_config`)
}

poppler_convert <- function(file_path, format, pages, names, dpi, opw, upw, antialiasing, text_antialiasing) {
  .Call(`_cpp11tesseract_poppler_convert`, file_path, format, pages, names, dpi, opw, upw, antialiasing, text_antialiasing)
}
