# Generated by cpp11: do not edit by hand

tesseract_major_version <- function() {
  .Call(`_readpdf_tesseract_major_version`)
}

tesseract_config <- function() {
  .Call(`_readpdf_tesseract_config`)
}

tesseract_engine_internal <- function(datapath, language, confpaths, opt_names, opt_values) {
  .Call(`_readpdf_tesseract_engine_internal`, datapath, language, confpaths, opt_names, opt_values)
}

tesseract_engine_set_variable <- function(ptr, name, value) {
  .Call(`_readpdf_tesseract_engine_set_variable`, ptr, name, value)
}

validate_params <- function(params) {
  .Call(`_readpdf_validate_params`, params)
}

engine_info_internal <- function(ptr) {
  .Call(`_readpdf_engine_info_internal`, ptr)
}

print_params <- function(filename) {
  .Call(`_readpdf_print_params`, filename)
}

get_param_values <- function(api, params) {
  .Call(`_readpdf_get_param_values`, api, params)
}

ocr_file <- function(file, ptr, HOCR) {
  .Call(`_readpdf_ocr_file`, file, ptr, HOCR)
}

n_pages <- function(file_path, opw, upw) {
  .Call(`_readpdf_n_pages`, file_path, opw, upw)
}

get_poppler_config <- function() {
  .Call(`_readpdf_get_poppler_config`)
}

poppler_convert <- function(file_path, format, pages, names, dpi, opw, upw, antialiasing, text_antialiasing) {
  .Call(`_readpdf_poppler_convert`, file_path, format, pages, names, dpi, opw, upw, antialiasing, text_antialiasing)
}
