# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.name }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-13,        r: 'release', name: 'MacOS 13 (release)'}
          - {os: macos-14,        r: 'release', name: 'MacOS 14 (release)'}
          - {os: windows-latest , r: 'release', name: 'Windows latest (release)'}
          - {os: windows-latest,  r: '4.1',     name: 'Windows latest (4.1)'}
          - {os: ubuntu-latest,   r: 'devel',   name: 'Ubuntu latest (devel)', http-user-agent: 'release'}
          - {os: ubuntu-24.04,    r: 'release', name: 'Ubuntu 24.04 (release)'}
          - {os: ubuntu-22.04,    r: 'release', name: 'Ubuntu 22.04 (release)'}
          - {os: ubuntu-20.04,    r: 'release', name: 'Ubuntu 20.04 (release)'}
          - {os: ubuntu-latest,   r: 'release', name: 'Fedora dockerized latest (release)', tag: 'fedora'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: Check if Fedora (Linux/Mac)
        if: runner.os != 'Windows'
        id: check_fedora
        run: echo "is_fedora=$([[ '${{ matrix.config.tag }}' == 'fedora' ]] && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Check if Fedora (Windows)
        if: runner.os == 'Windows'
        id: check_fedora_win
        run: echo "is_fedora=%[[$(if [ '${{ matrix.config.tag }}' == 'fedora' ]; then echo 'true'; else echo 'false'; fi)]%" >> $GITHUB_ENV
        shell: cmd

      - name: Run on Ubuntu/Mac/Windows
        if: env.is_fedora != 'true'
        uses: r-lib/actions/check-r-package@v2

      - name: Run on Fedora
        if: env.is_fedora == 'true'
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace fedora:latest bash -c "
            dnf install -y R R-devel libcurl-devel openssl-devel libxml2-devel &&
            R -e 'install.packages(c(\"remotes\", \"rcmdcheck\"), repos=\"https://cloud.r-project.org\")' &&
            R CMD check ."
