# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.name }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-13,        r: 'release', name: 'MacOS 13 (release)'}
          - {os: macos-14,        r: 'release', name: 'MacOS 14 (release)'}
          - {os: windows-latest , r: 'release', name: 'Windows latest (release)'}
          - {os: windows-latest,  r: '4.1',     name: 'Windows latest (4.1)'}
          - {os: ubuntu-latest,   r: 'devel',   name: 'Ubuntu latest (devel)', http-user-agent: 'release'}
          - {os: ubuntu-24.04,    r: 'release', name: 'Ubuntu 24.04 (release)'}
          - {os: ubuntu-22.04,    r: 'release', name: 'Ubuntu 22.04 (release)'}
          - {os: ubuntu-20.04,    r: 'release', name: 'Ubuntu 20.04 (release)'}
          - {os: ubuntu-latest, container: { image: 'ghcr.io/r-hub/containers/ubuntu-clang:latest' }, name: 'r-devel-linux-x86_64-debian-clang'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install pak (MacOS)
        if: matrix.config.os == 'macos-13' || matrix.config.os == 'macos-14'
        run: R -e 'install.packages("pak", repos = "https://cloud.r-project.org")'

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: Install system dependencies (Ubuntu)
        if: matrix.config.os == 'ubuntu-latest' || matrix.config.os == 'ubuntu-24.04' || matrix.config.os == 'ubuntu-22.04' || matrix.config.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libtesseract-dev libleptonica-dev libpoppler-cpp-dev

      - name: Install system dependencies (Windows)
        if: matrix.config.os == 'windows-latest'
        run: |
          choco install tesseract
          choco install poppler

      - name: Run on Ubuntu
        if: matrix.config.os == 'ubuntu-latest' || matrix.config.os == 'ubuntu-24.04' || matrix.config.os == 'ubuntu-22.04' || matrix.config.os == 'ubuntu-20.04'
        uses: r-lib/actions/check-r-package@v2

      - name: Run on MacOS
        if: matrix.config.os == 'macos-13' || matrix.config.os == 'macos-14'
        uses: r-lib/actions/check-r-package@v2

      - name: Run on Windows
        if: matrix.config.os == 'windows-latest'
        uses: r-lib/actions/check-r-package@v2
